### ISSUE TITLE
slimbookamdcontroller EXCALIBUR-16-AMD7

### ISSUE THREAD

**Issue by edumag** [Slimbook-Team/slimbook_service#21]
$ slimbookamdcontroller
Loading configuration:

- Autostart disabled
- Indicator enabled
Found thermal zone!
es
Setting cpu TDP values
Traceback (most recent call last):
  File "/usr/bin/slimbookamdcontroller", line 21, in <module>
    slimbookamdcontroller.main()
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 647, in main
    win = SlimbookAMD()
          ^^^^^^^^^^^^^
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 340, in __init__
    self.set_cpu()
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 578, in set_cpu
    params = db_cpu['PROCESSORS'][cpu_codename]
             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 1224, in __getitem__
    raise KeyError(key)
KeyError: 'Ryzen-7-7840HS'

------- info --------------

$ slimbookctl info
uptime:9h 23m 28s
kernel:Linux version 6.8.0-45-generic (buildd@lcy02-amd64-115) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024
memory free/total:19.13 GB/30.67 GB
disk free/total:/ 203.09 GB/233.67 GB
disk free/total:/boot/efi 291.50 MB/299.40 MB
boot mode: UEFI

product:EXCALIBUR-16-AMD7               
sku:0000000000000000
vendor:SLIMBOOK               
bios:SLIMH6.02
EC:1.3
serial:
cpu:AMD Ryzen 7 7840HS w/ Radeon 780M Graphics x 16
memory device:16384 MB 5600 MT/s
memory device:16384 MB 5600 MT/s

model:0x4002
platform:0x400
family:excalibur
module loaded:not needed

**Comment by Lt-Henry** [comment]
Perhaps this issue fits better on slimbookamdcontroller repo :D

Anyway, we are currently looking into it.
